<?php

namespace AppBundle\Repository;

/**
 * AppConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
