<?php

namespace AppBundle\Repository;

/**
 * RiskControlRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RisksControlsRepository extends \Doctrine\ORM\EntityRepository
{
}
