<?php

namespace AppBundle\Repository;

/**
 * WeatherTrendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherTrendRepository extends \Doctrine\ORM\EntityRepository
{
}
