nelmio_cors:
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
                max_age: 3600
            # '^/login-api/':
            #     allow_origin: ['*']
            #     allow_headers: ['*']
            #     allow_methods: ['POST']
            #     max_age: 3600